'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Check, Eye, FileImage, ImagePlus, Loader2, Save, TriangleAlert } from 'lucide-react'
import type { HomepageCategory, HomepageContent } from '@/lib/homepage-types'

type SectionKey = 'hero' | 'why' | 'products' | 'oem' | 'factory' | 'about' | 'testimonials' | 'contact'
type Status = 'idle' | 'saving' | 'saved' | 'error'

const sections: { key: SectionKey; label: string }[] = [
  { key: 'hero', label: 'Hero 主视觉' },
  { key: 'why', label: '品牌卖点' },
  { key: 'products', label: '产品分类与媒体' },
  { key: 'oem', label: 'OEM & ODM' },
  { key: 'factory', label: '工厂数据' },
  { key: 'about', label: '关于我们' },
  { key: 'testimonials', label: '客户评价' },
  { key: 'contact', label: '联系方式' },
]

function Field({ label, value, onChange, textarea = false, type = 'text', disabled = false }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean; type?: 'text' | 'url' | 'email'; disabled?: boolean }) {
  const className = 'mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition focus:border-[#ff6a00] focus:ring-4 focus:ring-orange-100 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500'
  return <label className="block text-sm font-semibold text-slate-700"><span>{label}</span>{textarea ? <textarea rows={4} className={className} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} /> : <input type={type} className={className} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)} />}</label>
}

function replaceAt<T>(items: T[], index: number, item: T) {
  return items.map((current, currentIndex) => currentIndex === index ? item : current)
}

function CategoryMediaEditor({ item, onChange, disabled }: { item: HomepageCategory; onChange: (item: HomepageCategory) => void; disabled: boolean }) {
  const [newImage, setNewImage] = useState('')
  const images = item.images.length ? item.images : [item.image]
  const updateImage = (index: number, value: string) => {
    const nextImages = replaceAt(images, index, value)
    onChange({ ...item, image: nextImages[0], images: nextImages })
  }
  const removeImage = (index: number) => {
    if (images.length === 1) return
    const nextImages = images.filter((_, imageIndex) => imageIndex !== index)
    onChange({ ...item, image: nextImages[0], images: nextImages })
  }
  const addImage = () => {
    const value = newImage.trim()
    if (!value) return
    onChange({ ...item, images: [...images, value] })
    setNewImage('')
  }
  return <div className="mt-5 border-t border-slate-200 pt-5"><div className="flex items-center gap-2"><FileImage className="size-4 text-[#ff6a00]" /><h4 className="text-sm font-bold text-slate-800">分类图片与视频</h4></div><p className="mt-1 text-xs leading-relaxed text-slate-500">第一张是分类卡封面；其余图片和视频会在首页媒体预览中保留展示。仅可使用站内路径或 HTTP(S) URL。</p><div className="mt-4 space-y-3">{images.map((image, index) => <div key={`${index}-${image}`} className="flex gap-2"><div className="min-w-0 flex-1"><Field label={index === 0 ? '封面图片 URL' : `附加图片 ${index + 1} URL`} type="url" value={image} disabled={disabled} onChange={(value) => updateImage(index, value)} /></div><button type="button" aria-label={`删除图片 ${index + 1}`} disabled={disabled || images.length === 1} onClick={() => removeImage(index)} className="mt-7 h-10 shrink-0 rounded-lg border border-slate-200 px-3 text-xs font-bold text-slate-600 hover:border-red-200 hover:bg-red-50 hover:text-red-700 disabled:cursor-not-allowed disabled:opacity-40">删除</button></div>)}</div><div className="mt-3 flex gap-2"><input aria-label="新增图片 URL" type="url" value={newImage} disabled={disabled} placeholder="新增图片 URL" onChange={(event) => setNewImage(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-[#ff6a00] disabled:bg-slate-100" /><button type="button" disabled={disabled || !newImage.trim()} onClick={addImage} className="inline-flex shrink-0 items-center gap-1 rounded-lg border border-orange-200 bg-orange-50 px-3 py-2 text-sm font-bold text-[#e85d00] hover:bg-orange-100 disabled:cursor-not-allowed disabled:opacity-50"><ImagePlus className="size-4" />添加图片</button></div><div className="mt-4"><Field label="视频 URL（可选）" type="url" value={item.video} disabled={disabled} onChange={(value) => onChange({ ...item, video: value })} /></div></div>
}

export function HomepageEditor({ initial, readOnly }: { initial: HomepageContent; readOnly: boolean }) {
  const [content, setContent] = useState(initial)
  const [active, setActive] = useState<SectionKey>('hero')
  const [status, setStatus] = useState<Status>('idle')
  const [message, setMessage] = useState('')
  const disabled = readOnly || status === 'saving'
  const update = <K extends SectionKey>(key: K, patch: Partial<HomepageContent[K]>) => setContent((current) => ({ ...current, [key]: { ...current[key], ...patch } }) as HomepageContent)
  const save = async () => {
    if (readOnly) return
    setStatus('saving')
    setMessage('')
    try {
      const response = await fetch('/api/homepage', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(content) })
      const payload = await response.json().catch(() => null) as { content?: HomepageContent; error?: string } | null
      if (!response.ok || !payload?.content) throw new Error(payload?.error || '保存失败，请稍后重试。')
      setContent(payload.content)
      setStatus('saved')
      setMessage('内容已保存为新的不可变版本，并将在首页读取。')
    } catch (error) {
      setStatus('error')
      setMessage(error instanceof Error ? error.message : '保存失败，请稍后重试。')
    }
  }
  const updateCategory = (index: number, item: HomepageCategory) => update('products', { items: replaceAt(content.products.items, index, item) })
  const activeLabel = sections.find((section) => section.key === active)?.label

  return <div className="mx-auto max-w-[1440px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#e85d00]">Homepage CMS</p><h1 className="mt-1 text-3xl font-bold tracking-tight">首页内容管理</h1><p className="mt-2 max-w-3xl text-sm text-slate-500">编辑公开首页文案、图片、分类媒体与联系方式。商品目录由独立的产品后台维护，不会在此保存。</p></div><div className="flex gap-2"><a href="/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50"><Eye className="size-4" />查看首页</a><button onClick={save} disabled={disabled} className="inline-flex items-center gap-2 rounded-lg bg-[#ff6a00] px-4 py-2.5 text-sm font-bold text-white hover:bg-[#e85d00] disabled:cursor-not-allowed disabled:opacity-60">{status === 'saving' ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}{readOnly ? '只读模式' : '保存首页'}</button></div></div>
    {readOnly && <div className="mt-6 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><TriangleAlert className="mt-0.5 size-5 shrink-0" /><div><p className="font-bold">首页 CMS 当前为只读</p><p className="mt-1">未检测到 Blob 持久化配置。首页仍显示已随部署提供的基线内容，但保存按钮已禁用，绝不会显示为发布成功。</p></div></div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[240px_minmax(0,1fr)]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-3 lg:sticky lg:top-24"><p className="px-3 pb-2 pt-1 text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">首页区块</p><nav className="space-y-1">{sections.map((section) => <button key={section.key} type="button" onClick={() => setActive(section.key)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm font-semibold transition ${active === section.key ? 'bg-orange-50 text-[#e85d00]' : 'text-slate-600 hover:bg-slate-50'}`}>{section.label}{active === section.key && <span className="size-2 rounded-full bg-[#ff6a00]" />}</button>)}</nav><div className="mt-5 rounded-lg bg-slate-900 p-4 text-xs leading-relaxed text-slate-300"><p className="font-bold text-orange-300">产品目录独立维护</p><p className="mt-1">新增、编辑和发布商品请前往产品后台；本编辑器不读取或写入 catalog/items。</p><Link href="/admin/products" className="mt-3 inline-block font-bold text-white underline underline-offset-2">打开 Products →</Link></div></aside><main className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm lg:p-7"><div className="mb-7 border-b border-slate-100 pb-5"><p className="text-sm font-semibold text-[#e85d00]">编辑区块</p><h2 className="mt-1 text-2xl font-bold">{activeLabel}</h2></div><EditorFields active={active} content={content} update={update} updateCategory={updateCategory} disabled={disabled} /><div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-slate-100 pt-6"><p role="status" className={`text-sm font-semibold ${status === 'error' ? 'text-red-700' : status === 'saved' ? 'text-emerald-700' : 'text-slate-500'}`}>{status === 'saved' && <Check className="mr-1 inline size-4" />}{message || (readOnly ? '配置 Blob 后即可保存首页内容。' : '保存会创建新的 Blob 版本；不会覆盖商品目录。')}</p><button onClick={save} disabled={disabled} className="inline-flex items-center gap-2 rounded-lg bg-[#ff6a00] px-5 py-3 text-sm font-bold text-white hover:bg-[#e85d00] disabled:cursor-not-allowed disabled:opacity-60"><Save className="size-4" />保存首页</button></div></main></div></div>
}

function EditorFields({ active, content, update, updateCategory, disabled }: { active: SectionKey; content: HomepageContent; update: <K extends SectionKey>(key: K, patch: Partial<HomepageContent[K]>) => void; updateCategory: (index: number, item: HomepageCategory) => void; disabled: boolean }) {
  if (active === 'hero') return <div className="grid gap-5 md:grid-cols-2"><Field label="顶部小标题" value={content.hero.eyebrow} disabled={disabled} onChange={(eyebrow) => update('hero', { eyebrow })} /><Field label="主标题" value={content.hero.title} disabled={disabled} onChange={(title) => update('hero', { title })} /><Field label="副标题" value={content.hero.subtitle} textarea disabled={disabled} onChange={(subtitle) => update('hero', { subtitle })} /><Field label="主按钮文字" value={content.hero.primaryCta} disabled={disabled} onChange={(primaryCta) => update('hero', { primaryCta })} /><Field label="次按钮文字" value={content.hero.secondaryCta} disabled={disabled} onChange={(secondaryCta) => update('hero', { secondaryCta })} /><Field label="背景图片 URL" type="url" value={content.hero.image} disabled={disabled} onChange={(image) => update('hero', { image })} /></div>
  if (active === 'why') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.why.eyebrow} disabled={disabled} onChange={(eyebrow) => update('why', { eyebrow })} /><Field label="主标题" value={content.why.title} disabled={disabled} onChange={(title) => update('why', { title })} /><Field label="描述" value={content.why.description} textarea disabled={disabled} onChange={(description) => update('why', { description })} /></div>{content.why.items.map((item, index) => <div key={index} className="rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="mb-4 text-sm font-bold text-slate-500">卖点 {index + 1}</p><div className="grid gap-4 md:grid-cols-2"><Field label="标题" value={item.title} disabled={disabled} onChange={(title) => update('why', { items: replaceAt(content.why.items, index, { ...item, title }) })} /><Field label="描述" value={item.text} textarea disabled={disabled} onChange={(text) => update('why', { items: replaceAt(content.why.items, index, { ...item, text }) })} /></div></div>)}</div>
  if (active === 'products') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.products.eyebrow} disabled={disabled} onChange={(eyebrow) => update('products', { eyebrow })} /><Field label="主标题" value={content.products.title} disabled={disabled} onChange={(title) => update('products', { title })} /><Field label="描述" value={content.products.description} textarea disabled={disabled} onChange={(description) => update('products', { description })} /></div>{content.products.items.map((item, index) => <div key={item.slug} className="rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="mb-4 text-sm font-bold text-slate-500">分类 {index + 1} · {item.slug}</p><div className="grid gap-4 md:grid-cols-2"><Field label="名称" value={item.name} disabled={disabled} onChange={(name) => updateCategory(index, { ...item, name })} /><Field label="描述" value={item.text} textarea disabled={disabled} onChange={(text) => updateCategory(index, { ...item, text })} /></div><CategoryMediaEditor item={item} disabled={disabled} onChange={(next) => updateCategory(index, next)} /></div>)}</div>
  if (active === 'oem') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.oem.eyebrow} disabled={disabled} onChange={(eyebrow) => update('oem', { eyebrow })} /><Field label="主标题" value={content.oem.title} disabled={disabled} onChange={(title) => update('oem', { title })} /><Field label="描述" value={content.oem.description} textarea disabled={disabled} onChange={(description) => update('oem', { description })} /><Field label="图片 URL" type="url" value={content.oem.image} disabled={disabled} onChange={(image) => update('oem', { image })} /><Field label="统计数值" value={content.oem.statValue} disabled={disabled} onChange={(statValue) => update('oem', { statValue })} /><Field label="统计标签" value={content.oem.statLabel} disabled={disabled} onChange={(statLabel) => update('oem', { statLabel })} /><Field label="按钮文字" value={content.oem.cta} disabled={disabled} onChange={(cta) => update('oem', { cta })} /></div>{content.oem.services.map((item, index) => <div key={index} className="grid gap-4 rounded-lg border border-slate-200 bg-slate-50 p-4 md:grid-cols-2"><Field label={`服务 ${index + 1} 标题`} value={item.title} disabled={disabled} onChange={(title) => update('oem', { services: replaceAt(content.oem.services, index, { ...item, title }) })} /><Field label="说明" value={item.text} textarea disabled={disabled} onChange={(text) => update('oem', { services: replaceAt(content.oem.services, index, { ...item, text }) })} /></div>)}</div>
  if (active === 'factory') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.factory.eyebrow} disabled={disabled} onChange={(eyebrow) => update('factory', { eyebrow })} /><Field label="主标题" value={content.factory.title} disabled={disabled} onChange={(title) => update('factory', { title })} /><Field label="描述" value={content.factory.description} textarea disabled={disabled} onChange={(description) => update('factory', { description })} /><Field label="图片 URL" type="url" value={content.factory.image} disabled={disabled} onChange={(image) => update('factory', { image })} /></div>{content.factory.stats.map((item, index) => <div key={index} className="grid gap-4 rounded-lg border border-slate-200 bg-slate-50 p-4 md:grid-cols-2"><Field label={`数据 ${index + 1}`} value={item.value} disabled={disabled} onChange={(value) => update('factory', { stats: replaceAt(content.factory.stats, index, { ...item, value }) })} /><Field label="标签" value={item.label} disabled={disabled} onChange={(label) => update('factory', { stats: replaceAt(content.factory.stats, index, { ...item, label }) })} /></div>)}</div>
  if (active === 'about') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.about.eyebrow} disabled={disabled} onChange={(eyebrow) => update('about', { eyebrow })} /><Field label="公司标题" value={content.about.title} disabled={disabled} onChange={(title) => update('about', { title })} /><Field label="公司介绍" value={content.about.description} textarea disabled={disabled} onChange={(description) => update('about', { description })} /><Field label="图片 URL" type="url" value={content.about.image} disabled={disabled} onChange={(image) => update('about', { image })} /><Field label="按钮文字" value={content.about.cta} disabled={disabled} onChange={(cta) => update('about', { cta })} /></div>{content.about.highlights.map((highlight, index) => <Field key={index} label={`要点 ${index + 1}`} value={highlight} disabled={disabled} onChange={(value) => update('about', { highlights: replaceAt(content.about.highlights, index, value) })} />)}</div>
  if (active === 'testimonials') return <div className="space-y-5"><div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.testimonials.eyebrow} disabled={disabled} onChange={(eyebrow) => update('testimonials', { eyebrow })} /><Field label="主标题" value={content.testimonials.title} disabled={disabled} onChange={(title) => update('testimonials', { title })} /></div>{content.testimonials.items.map((item, index) => <div key={index} className="space-y-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="text-sm font-bold text-slate-500">评价 {index + 1}</p><Field label="评价内容" value={item.quote} textarea disabled={disabled} onChange={(quote) => update('testimonials', { items: replaceAt(content.testimonials.items, index, { ...item, quote }) })} /><div className="grid gap-4 md:grid-cols-2"><Field label="客户姓名" value={item.name} disabled={disabled} onChange={(name) => update('testimonials', { items: replaceAt(content.testimonials.items, index, { ...item, name }) })} /><Field label="职位/公司" value={item.role} disabled={disabled} onChange={(role) => update('testimonials', { items: replaceAt(content.testimonials.items, index, { ...item, role })})} /></div></div>)}</div>
  return <div className="grid gap-5 md:grid-cols-2"><Field label="小标题" value={content.contact.eyebrow} disabled={disabled} onChange={(eyebrow) => update('contact', { eyebrow })} /><Field label="主标题" value={content.contact.title} disabled={disabled} onChange={(title) => update('contact', { title })} /><Field label="描述" value={content.contact.description} textarea disabled={disabled} onChange={(description) => update('contact', { description })} /><Field label="邮箱" type="email" value={content.contact.email} disabled={disabled} onChange={(email) => update('contact', { email })} /><Field label="WhatsApp" value={content.contact.whatsapp} disabled={disabled} onChange={(whatsapp) => update('contact', { whatsapp })} /><Field label="WhatsApp 链接" type="url" value={content.contact.whatsappLink} disabled={disabled} onChange={(whatsappLink) => update('contact', { whatsappLink })} /><Field label="地址" value={content.contact.address} textarea disabled={disabled} onChange={(address) => update('contact', { address })} /></div>
}
